%% function taken from lab 6 solutions
function dist=dist2pts(pt1,pt2)

    %% Calculate distance (dist) between consecutive points
    % If 2D
    if size(pt1,2) == 2
        dist=sqrt((pt1(:,1)-pt2(:,1)).^2+...
                  (pt1(:,2)-pt2(:,2)).^2);
    % If 3D          
    elseif size(pt1,2) == 3
        dist=sqrt((pt1(:,1)-pt2(:,1)).^2+...
                  (pt1(:,2)-pt2(:,2)).^2+...
                  (pt1(:,3)-pt2(:,3)).^2);
    % If 6D like two poses
    elseif size(pt1,2) == 6
        dist=sqrt((pt1(:,1)-pt2(:,1)).^2+...
                  (pt1(:,2)-pt2(:,2)).^2+...
                  (pt1(:,3)-pt2(:,3)).^2+...
                  (pt1(:,4)-pt2(:,4)).^2+...
                  (pt1(:,5)-pt2(:,5)).^2+...
                  (pt1(:,6)-pt2(:,6)).^2);
    end
end


